#author: @ManasaViswandhuni
---
- hosts: eos_demo_group
  gather_facts: no
  connection: local
  tasks:
    - name: veos show version
      eos_command:
        host: "{{inventory_hostname}}"
        provider: "{{ provider }}"
        commands: show startup-config
      register: show
    - name: saving output
      copy:
        content: "{{show.stdout[0]}}"
        dest: "./backups/show_{{ inventory_hostname }}.txt"
    - name: commandss
      eos_config:
         host: "{{inventory_hostname}}"
         provider: "{{ provider }}"
         lines:
           - int Management 1
           - shut
      register: conf
    - name: show output
      eos_command:
        provider: "{{ provider }}"
        commands: show ip int br
      register: shows
    - name: saving output
      copy:
        content: "{{shows.stdout[0]}}"
        dest: "./backups/show_int_{{ inventory_hostname }}.txt" 
          
   
